name: check

on: push

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.12"
      - run: poetry install
      - run: mypy .
      - run: black .
      - run: flake8 .
      - run: pylint basedtyping tests
      - run: pytest
